// packages
import Head from 'next/head';

const SEO = () => {
	return (
		<Head>
			<meta charSet="utf-8" />
			<meta name="theme-color" content="#ffffff" />
			<meta
				name="viewport"
				content="width=device-width, initial-scale=1.0"
			/>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			<title>Next.js Weather API</title>
			<link rel="preconnect" href="https://fonts.googleapis.com" />
			<link
				rel="preconnect"
				href="https://fonts.gstatic.com"
				crossorigin
			/>
			<link
				href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;600;700;800&display=swap"
				rel="stylesheet"
			/>
		</Head>
	);
};

export default SEO;
